//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamAchievements {
    
    
    public partial class Publish {
        
        /// <summary>
        /// steamUserIdHidden control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField steamUserIdHidden;
        
        /// <summary>
        /// steamIdErrorSettingsLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SteamAchievements.Controls.CanvasLink steamIdErrorSettingsLink;
        
        /// <summary>
        /// steamIdErrorHelpLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SteamAchievements.Controls.HelpLink steamIdErrorHelpLink;
        
        /// <summary>
        /// updateFailedHelpLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SteamAchievements.Controls.HelpLink updateFailedHelpLink;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new SteamAchievements.Site Master {
            get {
                return ((SteamAchievements.Site)(base.Master));
            }
        }
    }
}
