//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamAchievements.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SteamAchievements.Web.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string ButtonHelp {
            get {
                return ResourceManager.GetString("ButtonHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string ButtonHide {
            get {
                return ResourceManager.GetString("ButtonHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string ButtonPublish {
            get {
                return ResourceManager.GetString("ButtonPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the publish page to update and publish new achievements to your profile..
        /// </summary>
        public static string GamesIntructions {
            get {
                return ResourceManager.GetString("GamesIntructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Achievements.
        /// </summary>
        public static string GamesViewAchievements {
            get {
                return ResourceManager.GetString("GamesViewAchievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your games. This list includes all Steam games that you own (including some free Source Mods) that support achievements..
        /// </summary>
        public static string GamesYourGames {
            get {
                return ResourceManager.GetString("GamesYourGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string MenuPublish {
            get {
                return ResourceManager.GetString("MenuPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click an achievement icon to select it. You can select up to five at a time. If you don&apos;t see the publish dialog after clicking Publish, scroll down. If you hide an achievement, you will no longer see it on this page and it can not be published..
        /// </summary>
        public static string PublishInstructions {
            get {
                return ResourceManager.GetString("PublishInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpublished Achievements.
        /// </summary>
        public static string PublishUnpublishedAchievements {
            get {
                return ResourceManager.GetString("PublishUnpublishedAchievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update and publish my achievements automatically..
        /// </summary>
        public static string SettingsAutoUpdateLabel {
            get {
                return ResourceManager.GetString("SettingsAutoUpdateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Community Custom URL.
        /// </summary>
        public static string SettingsCustomUrl {
            get {
                return ResourceManager.GetString("SettingsCustomUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include achievement descriptions when publishing..
        /// </summary>
        public static string SettingsPublishDescriptionLabel {
            get {
                return ResourceManager.GetString("SettingsPublishDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Options.
        /// </summary>
        public static string SettingsPublishOptions {
            get {
                return ResourceManager.GetString("SettingsPublishOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string TitleGames {
            get {
                return ResourceManager.GetString("TitleGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string TitleHome {
            get {
                return ResourceManager.GetString("TitleHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string TitlePublish {
            get {
                return ResourceManager.GetString("TitlePublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string TitleSettings {
            get {
                return ResourceManager.GetString("TitleSettings", resourceCulture);
            }
        }
    }
}
