// <auto-generated />
namespace SteamAchievements.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class steam_UserSteamUserIdNotRequiredAddIndex : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(steam_UserSteamUserIdNotRequiredAddIndex));
        
        string IMigrationMetadata.Id
        {
            get { return "201608012132482_steam_UserSteamUserIdNotRequiredAddIndex"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
