<?xml version="1.0" encoding="utf-8"?><Database Name="steam" Class="SteamDataContext" AccessModifier="Internal" Serialization="Unidirectional" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost\SQLEXPRESS;Initial Catalog=Steam;Integrated Security=True" SettingsObjectName="SteamAchievements.Data.Properties.Settings" SettingsPropertyName="steamConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.steam_Achievement" Member="Achievements">
    <Type Name="Achievement">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GameId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="ImageUrl" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Association Name="Achievement_UserAchievement" Member="UserAchievements" Storage="_steam_UserAchievements" ThisKey="Id" OtherKey="AchievementId" Type="UserAchievement" />
    </Type>
  </Table>
  <Table Name="dbo.steam_UserAchievement" Member="UserAchievements">
    <Type Name="UserAchievement">
      <Column Name="Id" Type="System.Int32" DbType="int not null" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SteamUserId" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AchievementId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="datetime not null" CanBeNull="false" />
      <Column Name="Published" Type="System.Boolean" DbType="bit not null" CanBeNull="false" />
      <Association Name="Achievement_UserAchievement" Member="Achievement" Storage="_steam_Achievement" ThisKey="AchievementId" OtherKey="Id" Type="Achievement" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.steam_User" Member="Users">
    <Type Name="User">
      <Column Name="FacebookUserId" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SteamUserId" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>